# ---------- Database ----------
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/portalapplication?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC


spring.security.oauth2.client.registration.wso2.client-id=u_nu9792IH6g7cgucHRTbpdhes8a

spring.security.oauth2.client.registration.wso2.client-secret=q0aph7L9dOLfoWzlRV89xjNYvWfIxd_awWcAASJCHJsa

spring.security.oauth2.client.registration.wso2.scope=openid,profile,email

spring.security.oauth2.client.registration.wso2.authorization-grant-type=authorization_code

spring.security.oauth2.client.registration.wso2.redirect-uri=http://localhost:8080/login/oauth2/code/wso2


spring.security.oauth2.client.registration.wso2.client-name=WSO2


# =========================================
# WSO2 PROVIDER
# =========================================

spring.security.oauth2.client.provider.wso2.authorization-uri=https://wso2.cnxy.in/oauth2/authorize

spring.security.oauth2.client.provider.wso2.token-uri=https://wso2.cnxy.in/oauth2/token

spring.security.oauth2.client.provider.wso2.user-info-uri=https://wso2.cnxy.in/oauth2/userinfo

spring.security.oauth2.client.provider.wso2.jwk-set-uri=https://wso2.cnxy.in/oauth2/jwks

spring.security.oauth2.client.provider.wso2.user-name-attribute=given_name


# =========================================
# LOGGING
# =========================================

logging.level.org.springframework.security=DEBUG

logging.level.org.springframework.web=DEBUG

wso2.logout-url=https://wso2.cnxy.in/oidc/logout 
app.post-logout-url=http://localhost:8080/logout-success
# =========================================
# SESSION
# =========================================

server.servlet.session.timeout=30m